baseURL = "https://westtechair.com"
languageCode = "en-us"
title = "West Tech Air Heating & Cooling"
copyright = "Copyright &copy; {year}. West Tech Air All Rights Reserved"
permalinks = "/:slug/"

preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = "GTM-MB8W7XJ"
  disallow_search_engines = false # Set to true to disallow search engines from indexing your site
  noindex_kinds = [
    "taxonomy",
    "taxonomyTerm"
  ]

disableKinds = ["taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[params.homepage]
show_contact_box = false     # show / hide the contaxt box on the homepage
show_contact_form = true     # show / hide the contact form on the homepage
show_services_button = false # show / hide the "view all services" button

[params.logo]
mobile = "images/logo/west-tech-air.png"
mobile_height = "96"
mobile_width = "275"
alt = "West Tech Air"

[params.team]
summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

[params.footer]
copyright_text = 'West Tech Air © 2022. All Rights Reserved'
show_contact_box = false     # show / hide the contaxt box on the footer
show_services_button = false # show / hide the "view all services" button

[menu]
  # Main Menu

  [[menu.main]]
    name = "Services"
    url = "#"
    weight = 1

  [[menu.main]]
    name = "Furnace Repair and Replacement"
    url = "/furnace-repair-and-replacement/"
    weight = 2
    parent = "Services"

  [[menu.main]]
    name = "AC Repair and Replacement"
    url = "/ac-repair-and-replacement/"
    weight = 3
    parent = "Services"

  [[menu.main]]
    name = "Heat Pump Repair and Replacement"
    url = "/heat-pump-repair-and-replacement/"
    weight = 4
    parent = "Services"

  [[menu.main]]
    name = "Ductless Systems"
    url = "/ductless-systems/"
    weight = 5
    parent = "Services"

  [[menu.main]]
    name = "HVAC System Preventative Maintenance"
    url = "/hvac-system-preventative-maintenance/"
    weight = 6
    parent = "Services"

  [[menu.main]]
    name = "About Us"
    url = "/about-us/"
    weight = 7

  [[menu.main]]
    name = "Contact Us"
    url = "/contact-us/"
    weight = 8

  # Footer Menu
  # [[menu.footer]]
  #   name = "Home"
  #   url = "/"
  #   weight = 1

  # [[menu.footer]]
  #   name = "Contact Us"
  #   url = "/contact-us/"
  #   weight = 2